//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovGogolevDM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        public Assets()
        {
            this.AssetTransfers = new HashSet<AssetTransfers>();
        }
    
        public int AssetID { get; set; }
        public string AssetName { get; set; }
        public int CategoryID { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public decimal Cost { get; set; }
        public string Status { get; set; }
        public int AssignedTo { get; set; }
        public int DepartmentID { get; set; }
    
        public virtual AssetCategories AssetCategories { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual ICollection<AssetTransfers> AssetTransfers { get; set; }
    }
}
