//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovGogolevDM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCategories
    {
        public AssetCategories()
        {
            this.Assets = new HashSet<Assets>();
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<Assets> Assets { get; set; }
    }
}
