//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovGogolevDM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetTransfers
    {
        public int TransferID { get; set; }
        public int AssetID { get; set; }
        public int FromDepartmentID { get; set; }
        public int ToDepartmentID { get; set; }
        public System.DateTime TransferDate { get; set; }
        public int TransferredBy { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Departments Departments1 { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
