//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovGogolevDM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        public Departments()
        {
            this.Assets = new HashSet<Assets>();
            this.AssetTransfers = new HashSet<AssetTransfers>();
            this.AssetTransfers1 = new HashSet<AssetTransfers>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
    
        public virtual ICollection<Assets> Assets { get; set; }
        public virtual ICollection<AssetTransfers> AssetTransfers { get; set; }
        public virtual ICollection<AssetTransfers> AssetTransfers1 { get; set; }
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
