//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IvanovGogolevDM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Assets = new HashSet<Assets>();
            this.AssetTransfers = new HashSet<AssetTransfers>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int PositionID { get; set; }
        public int DepartmentID { get; set; }
        public System.DateTime HireDate { get; set; }
    
        public virtual ICollection<Assets> Assets { get; set; }
        public virtual ICollection<AssetTransfers> AssetTransfers { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual Positions Positions { get; set; }
    }
}
